version: "3.8"
services:

  adroid_ea:
    image: adanea/adroid_ea:test
    container_name: adroid_ea
    environment:
      - MONGO_URI=xxx
      - DISCORD_TOKEN=xxx
      - DISCORD_CLIENT_ID=xxx
      - TWITCH_CLIENT_ID=xxx
      - TWITCH_CLIENT_SECRET=xxx
      - REDIS_HOST=xxx
      - NODE_ENV=production
    restart: unless-stopped
    depends_on:
      - mongo
      - redis
  mongo:
    image: mongo
    container_name: database
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    restart: unless-stopped
    volumes:
      - /home/adanea/Documents/Docker/volumes:/data/db

  mongo-express:
    image: mongo-express
    container_name: admin-interface
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
    restart: unless-stopped
    depends_on:
      - mongo

  redis:
    image: redis/redis-stack
    container_name: redis
    restart: unless-stopped
    ports:
      - 6379:6379
      - 8001:8001
