version: "3.8"
services:

  adroid_ea:
    image: adanea/adroid_ea:test
    container_name: adroid_ea
    environment:
      - MONGO_URI=xxx
      - DISCORD_TOKEN=xxx
      - DISCORD_CLIENT_ID=xxx
      - TWITCH_CLIENT_ID=xxx
      - TWITCH_CLIENT_SECRET=xxx
    restart: unless-stopped
    depends_on:
      - mongo

  mongo:
    image: mongo
    container_name: database
    environment:
      MONGO_INITDB_ROOT_USERNAME: xxx
      MONGO_INITDB_ROOT_PASSWORD: xxx
      MONGO_INITDB_DATABASE: adroidDB
    restart: unless-stopped
    volumes:
      - adroidDB:/home/adanea/Documents/Docker/volumes

  mongo-express:
    image: mongo-express
    container_name: admin-interface
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: xxx
      ME_CONFIG_MONGODB_ADMINPASSWORD: xxx
      ME_CONFIG_MONGODB_URL: xxx
    restart: unless-stopped
    depends_on:
      - mongo

volumes:
  adroidDB:
