name: Docker Image CI

on:
  push:
    branches:
      - 4-upgrade-to-typescript

jobs:
  build_push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Install TypeScript
        run: npm install --no-save typescript && npx tsc

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag adanea/adroid_ea:test

      - name: docker login
        run: echo '${{ secrets.DOCKER_TOKEN }}' | docker login --username adanea --password-stdin

      - name: docker push
        run: docker push adanea/adroid_ea:test

