name: Docker Image CI
on:
  push:
    tags:
      - "*"

jobs:
  build_push:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v3

      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Install TypeScript
        run: npm install --no-save typescript && npx tsc

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag adanea/adroid_ea:$RELEASE_VERSION && docker tag adanea/adroid_ea:$RELEASE_VERSION adanea/adroid_ea:latest

      - name: docker login
        run: echo '${{ secrets.DOCKER_TOKEN }}' | docker login --username adanea --password-stdin

      - name: docker push
        run: docker push adanea/adroid_ea:$RELEASE_VERSION && docker push adanea/adroid_ea:latest

      - name: Build
        run: echo ${{ github.sha }} > Release.txt

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            Release.txt
      - name: Discord notifications
        uses: cl8dep/action-discord@main
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          message: "Build de l'image adanea/adroid_ea:$RELEASE_VERSION terminé"
