name: Codecov

on:
  push:
    branches:
      - 4-upgrade-to-typescript
  pull_request:
    branches:
      - 4-upgrade-to-typescript

jobs:
  codecov-tests:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:latest
        ports:
          - 27017:27017

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci

      - name: Run integration tests
        run: npm test
        env:
          MONGO_URI: mongodb://localhost:27017/

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
