name: Analyse qualité
on:
  push:
    branches:
      - 4-upgrade-to-typescript
  pull_request:
    types: [opened, synchronize, reopened]
    branches: ["4-upgrade-to-typescript"]
jobs:
  #---------------------------------------------------------------------------------------------------------------
  # SonarCloud : Analyse qualité du code
  #---------------------------------------------------------------------------------------------------------------
  sonarcloud:
    name: Analyse Qualité SonarCloud
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.sonar_status.outputs.status }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Shallow clones should be disabled for a better relevancy of analysis

      # Intégration Eslint à Sonar
      - name: Install dependencies
        run: npm ci

      - name: Install ESLint
        run: |
          npm install eslint@8.10.0
          npm install @microsoft/eslint-formatter-sarif@2.1.7

      - name: Run ESLint #Ignorer les dépendances externes
        run: npx eslint src/**/*.ts --format=json --ignore-pattern '**/node_modules/**' > eslint-report.json

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@de2e56b42aa84d0b1c5b622644ac17e505c9a049
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }} # Token GITHUB pour les PR
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} # Token SonarCloud
        with:
          # Autres args Sonar
          args:
            -Dsonar.projectKey=adan-ea_adroid_ea
            -Dsonar.organization=adanea-adroid-ea
            -Dsonar.eslint.reportPaths=eslint-report.json

      - name: SonarCloud Quality Gate status
        id: sonar_status
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          quality_gate_status=$(curl -s -u "${{ secrets.SONAR_TOKEN }}:" -X GET \
                               "https://sonarcloud.io/api/qualitygates/project_status?projectKey=adan-ea_adroid_ea")
          echo "$quality_gate_status"
          status=$(echo "$quality_gate_status" | cut -c 29-30)
          echo "result=$status" >> "$GITHUB_OUTPUT"
          echo "$status"

      - name: Discord notifications Ok
        if: ${{ steps.sonar_status.outputs.result == 'OK' }}
        uses: cl8dep/action-discord@main
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          message: "Analyse SonarCloud complétée pour le projet Adroid_ea pour les nouvelles lignes de codes. Statut : Ok. Pour consulter le rapport : https://sonarcloud.io/project/overview?id=adan-ea_adroid_ea&branch=4-upgrade-to-typescript"

      - name: Discord notifications NOT OK
        if: ${{ steps.sonar_status.outputs.result != 'OK' }}
        uses: cl8dep/action-discord@main
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          message: "Analyse sonar failed. Pour consulter le rapport : https://sonarcloud.io/project/overview?id=adan-ea_adroid_ea&branch=4-upgrade-to-typescript"

      - name: Write to workflow job summary
        run: |
          SUMMARY=$'# Testing Job Summary\n## Résultat Sonar\n${{ steps.sonar_status.outputs.result == 'OK' }}'
          echo "$SUMMARY" >> $GITHUB_STEP_SUMMARY
  #---------------------------------------------------------------------------------------------------------------
  # ESLint : Analyse de code statique TS
  #---------------------------------------------------------------------------------------------------------------
  eslint:
    name: Analyse eslint
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install ESLint
        run: |
          npm install eslint@8.35.0 --no-save
          npm install @microsoft/eslint-formatter-sarif@2.1.7 --no-save

      - name: Run ESLint
        run: npx eslint .
          --config .eslintrc.js
          --ext .ts
          --format @microsoft/eslint-formatter-sarif
          --output-file eslint-results.sarif
        continue-on-error: true

      - name: Upload analysis results to GitHub
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: eslint-results.sarif
          wait-for-processing: true
      - name: Discord notifications
        uses: cl8dep/action-discord@main
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          message: "Analyse Eslint terminée"
